"""update user

Revision ID: 182126865cf4
Revises: 3df848fa09a8
Create Date: 2023-06-22 01:50:38.679783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182126865cf4'
down_revision = '3df848fa09a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
