"""add socials

Revision ID: 2091f58b9340
Revises: 
Create Date: 2023-01-20 01:07:55.851534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2091f58b9340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_profile')
    op.drop_column('users', 'twitter_profile')
    op.drop_column('users', 'github_profile')
    # ### end Alembic commands ###
