"""empty message

Revision ID: 32929f03f637
Revises: f829d127d1cf
Create Date: 2023-05-02 10:53:01.913020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32929f03f637'
down_revision = 'f829d127d1cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    # ### end Alembic commands ###
