"""first revision

Revision ID: 62987cc2e0e4
Revises: 
Create Date: 2022-12-22 10:05:44.932217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62987cc2e0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
