"""username null and skills user id

Revision ID: 82074bee8581
Revises: c316e4df7722
Create Date: 2023-11-16 15:46:24.965166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82074bee8581'
down_revision = 'c316e4df7722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skills_name_key', 'skills', type_='unique')
    op.drop_constraint('skills_user_id_fkey', 'skills', type_='foreignkey')
    op.drop_column('skills', 'user_id')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('skills', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('skills_user_id_fkey', 'skills', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('skills_name_key', 'skills', ['name'])
    # ### end Alembic commands ###
