"""added endpoints table

Revision ID: 894654515194
Revises: 32df0260ed96
Create Date: 2024-05-20 12:03:08.574225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '894654515194'
down_revision = '32df0260ed96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('toggled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_email_templates_id', table_name='email_templates')
    op.drop_index('ix_email_templates_template_name', table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('html_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_templates_pkey')
    )
    op.create_index('ix_email_templates_template_name', 'email_templates', ['template_name'], unique=False)
    op.create_index('ix_email_templates_id', 'email_templates', ['id'], unique=False)
    op.drop_table('endpoints')
    # ### end Alembic commands ###
