"""technical task

Revision ID: 899d03339951
Revises: 1f9ec35e8650
Create Date: 2024-02-20 00:47:02.228514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899d03339951'
down_revision = '1f9ec35e8650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.Enum('JUNIOR', 'MID_LEVEL', 'SENIOR', name='experiencelevel'), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('github_link', sa.Text(), nullable=True),
    sa.Column('live_demo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['technical_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'skills', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_table('technical_task_submissions')
    op.drop_table('technical_tasks')
    # ### end Alembic commands ###
