"""include socials

Revision ID: 8c2308e15cec
Revises: 7ad775b30557
Create Date: 2023-01-19 22:54:46.787786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2308e15cec'
down_revision = '7ad775b30557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_profile')
    op.drop_column('users', 'twitter_profile')
    op.drop_column('users', 'github_profile')
    # ### end Alembic commands ###
