"""empty message

Revision ID: 989b73d3767a
Revises: b8c70e939795
Create Date: 2023-05-01 09:35:56.849944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b73d3767a'
down_revision = 'b8c70e939795'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yoe', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'yoe')
    # ### end Alembic commands ###
