"""remaned yoe to years_of_experience

Revision ID: e9f518ec19bf
Revises: 3d63981c2389
Create Date: 2023-05-05 09:04:30.879746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f518ec19bf'
down_revision = '3d63981c2389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
