"""empty message

Revision ID: f829d127d1cf
Revises: 989b73d3767a
Create Date: 2023-05-02 09:18:24.006573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f829d127d1cf'
down_revision = '989b73d3767a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
