name: CRM API BUILD AND TEST
on:
  pull_request:
    types: [opened]
    
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: 3.10

        - name: Install pytest
          run: pip install pytest

        - name: Test with pytest
          run: pytest
