name: CRM API BUILD AND TEST
on:
  pull_request:
    types: [opened, synchronize]

# command to run

jobs:
  deploy:
      name: Build and Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.9

        - name: Install pytest
          run: pip install pytest

        - name: Run poetry
          run: |
            pip install --upgrade poetry==1.2.2
            poetry install

        - name: Test with pytest
          run: pytest
