name: BUILD AND TEST
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
      name: Build and Test
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: github_actions_db
          ports:
            - 5432:5432
            
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry pytest
            poetry config virtualenvs.create false
            poetry install

        - name: Test with pytest
          run: |
            pytest
